// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBigpcBMPj2ZvSuKulau0l7oT_b8IGHzOg',
    appId: '1:169462121165:web:213090c7b47368df959f84',
    messagingSenderId: '169462121165',
    projectId: 'sampleproject-e01e5',
    authDomain: 'sampleproject-e01e5.firebaseapp.com',
    storageBucket: 'sampleproject-e01e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZxObWAghcqDeKyymcaPiBei0ltG0GTpM',
    appId: '1:169462121165:android:59248cb89275dd03959f84',
    messagingSenderId: '169462121165',
    projectId: 'sampleproject-e01e5',
    storageBucket: 'sampleproject-e01e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgLpn9gWjwLLCZrLuZNOUj62S1rvMF_1w',
    appId: '1:169462121165:ios:b1fa81c871c25165959f84',
    messagingSenderId: '169462121165',
    projectId: 'sampleproject-e01e5',
    storageBucket: 'sampleproject-e01e5.firebasestorage.app',
    iosBundleId: 'com.example.timeTracker',
  );
}
